// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: guest/v2/channel.proto

package guestchannelv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChannelDirection int32

const (
	ChannelDirection_CHANNEL_DIRECTION_UNSPECIFIED   ChannelDirection = 0
	ChannelDirection_CHANNEL_DIRECTION_HOST_TO_GUEST ChannelDirection = 1
	ChannelDirection_CHANNEL_DIRECTION_GUEST_TO_HOST ChannelDirection = 2
)

// Enum value maps for ChannelDirection.
var (
	ChannelDirection_name = map[int32]string{
		0: "CHANNEL_DIRECTION_UNSPECIFIED",
		1: "CHANNEL_DIRECTION_HOST_TO_GUEST",
		2: "CHANNEL_DIRECTION_GUEST_TO_HOST",
	}
	ChannelDirection_value = map[string]int32{
		"CHANNEL_DIRECTION_UNSPECIFIED":   0,
		"CHANNEL_DIRECTION_HOST_TO_GUEST": 1,
		"CHANNEL_DIRECTION_GUEST_TO_HOST": 2,
	}
)

func (x ChannelDirection) Enum() *ChannelDirection {
	p := new(ChannelDirection)
	*p = x
	return p
}

func (x ChannelDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_guest_v2_channel_proto_enumTypes[0].Descriptor()
}

func (ChannelDirection) Type() protoreflect.EnumType {
	return &file_guest_v2_channel_proto_enumTypes[0]
}

func (x ChannelDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelDirection.Descriptor instead.
func (ChannelDirection) EnumDescriptor() ([]byte, []int) {
	return file_guest_v2_channel_proto_rawDescGZIP(), []int{0}
}

// ProvisionChannel is delivered once over a LocalSystem-only Hyper-V socket.
// The channel key and nonces are generated with the operating-system CSPRNG and
// exist only for one VM boot. They are never persisted or placed in HCS JSON.
type ProvisionChannel struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	BootId          []byte                 `protobuf:"bytes,2,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	ChannelKey      []byte                 `protobuf:"bytes,3,opt,name=channel_key,json=channelKey,proto3" json:"channel_key,omitempty"`
	HostNonce       []byte                 `protobuf:"bytes,4,opt,name=host_nonce,json=hostNonce,proto3" json:"host_nonce,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProvisionChannel) Reset() {
	*x = ProvisionChannel{}
	mi := &file_guest_v2_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionChannel) ProtoMessage() {}

func (x *ProvisionChannel) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v2_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionChannel.ProtoReflect.Descriptor instead.
func (*ProvisionChannel) Descriptor() ([]byte, []int) {
	return file_guest_v2_channel_proto_rawDescGZIP(), []int{0}
}

func (x *ProvisionChannel) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ProvisionChannel) GetBootId() []byte {
	if x != nil {
		return x.BootId
	}
	return nil
}

func (x *ProvisionChannel) GetChannelKey() []byte {
	if x != nil {
		return x.ChannelKey
	}
	return nil
}

func (x *ProvisionChannel) GetHostNonce() []byte {
	if x != nil {
		return x.HostNonce
	}
	return nil
}

// ProvisionChannelAck proves the guest received the ephemeral channel key.
type ProvisionChannelAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	BootId          []byte                 `protobuf:"bytes,2,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	GuestNonce      []byte                 `protobuf:"bytes,3,opt,name=guest_nonce,json=guestNonce,proto3" json:"guest_nonce,omitempty"`
	HmacSha256      []byte                 `protobuf:"bytes,4,opt,name=hmac_sha256,json=hmacSha256,proto3" json:"hmac_sha256,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProvisionChannelAck) Reset() {
	*x = ProvisionChannelAck{}
	mi := &file_guest_v2_channel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionChannelAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionChannelAck) ProtoMessage() {}

func (x *ProvisionChannelAck) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v2_channel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionChannelAck.ProtoReflect.Descriptor instead.
func (*ProvisionChannelAck) Descriptor() ([]byte, []int) {
	return file_guest_v2_channel_proto_rawDescGZIP(), []int{1}
}

func (x *ProvisionChannelAck) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ProvisionChannelAck) GetBootId() []byte {
	if x != nil {
		return x.BootId
	}
	return nil
}

func (x *ProvisionChannelAck) GetGuestNonce() []byte {
	if x != nil {
		return x.GuestNonce
	}
	return nil
}

func (x *ProvisionChannelAck) GetHmacSha256() []byte {
	if x != nil {
		return x.HmacSha256
	}
	return nil
}

// ProvisionChannelProof is the deterministic protobuf body authenticated by
// ProvisionChannelAck. It deliberately excludes the channel key and the proof
// itself while binding both independently generated nonces to the boot.
type ProvisionChannelProof struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	BootId          []byte                 `protobuf:"bytes,2,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	HostNonce       []byte                 `protobuf:"bytes,3,opt,name=host_nonce,json=hostNonce,proto3" json:"host_nonce,omitempty"`
	GuestNonce      []byte                 `protobuf:"bytes,4,opt,name=guest_nonce,json=guestNonce,proto3" json:"guest_nonce,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProvisionChannelProof) Reset() {
	*x = ProvisionChannelProof{}
	mi := &file_guest_v2_channel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionChannelProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionChannelProof) ProtoMessage() {}

func (x *ProvisionChannelProof) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v2_channel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionChannelProof.ProtoReflect.Descriptor instead.
func (*ProvisionChannelProof) Descriptor() ([]byte, []int) {
	return file_guest_v2_channel_proto_rawDescGZIP(), []int{2}
}

func (x *ProvisionChannelProof) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ProvisionChannelProof) GetBootId() []byte {
	if x != nil {
		return x.BootId
	}
	return nil
}

func (x *ProvisionChannelProof) GetHostNonce() []byte {
	if x != nil {
		return x.HostNonce
	}
	return nil
}

func (x *ProvisionChannelProof) GetGuestNonce() []byte {
	if x != nil {
		return x.GuestNonce
	}
	return nil
}

// AuthenticatedPayload deliberately contains no maps. Implementations use
// deterministic protobuf serialization and a protocol-domain prefix as the MAC
// input. control_frame is the exact bounded guest-control payload during the v2
// migration; it is authenticated before JSON decoding.
type AuthenticatedPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	BootId          []byte                 `protobuf:"bytes,2,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	Direction       ChannelDirection       `protobuf:"varint,3,opt,name=direction,proto3,enum=grok.desktop.guest.v2.ChannelDirection" json:"direction,omitempty"`
	Sequence        uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	RequestId       string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DeadlineUnixMs  uint64                 `protobuf:"varint,6,opt,name=deadline_unix_ms,json=deadlineUnixMs,proto3" json:"deadline_unix_ms,omitempty"`
	ControlFrame    []byte                 `protobuf:"bytes,7,opt,name=control_frame,json=controlFrame,proto3" json:"control_frame,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthenticatedPayload) Reset() {
	*x = AuthenticatedPayload{}
	mi := &file_guest_v2_channel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticatedPayload) ProtoMessage() {}

func (x *AuthenticatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v2_channel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticatedPayload.ProtoReflect.Descriptor instead.
func (*AuthenticatedPayload) Descriptor() ([]byte, []int) {
	return file_guest_v2_channel_proto_rawDescGZIP(), []int{3}
}

func (x *AuthenticatedPayload) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *AuthenticatedPayload) GetBootId() []byte {
	if x != nil {
		return x.BootId
	}
	return nil
}

func (x *AuthenticatedPayload) GetDirection() ChannelDirection {
	if x != nil {
		return x.Direction
	}
	return ChannelDirection_CHANNEL_DIRECTION_UNSPECIFIED
}

func (x *AuthenticatedPayload) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *AuthenticatedPayload) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AuthenticatedPayload) GetDeadlineUnixMs() uint64 {
	if x != nil {
		return x.DeadlineUnixMs
	}
	return 0
}

func (x *AuthenticatedPayload) GetControlFrame() []byte {
	if x != nil {
		return x.ControlFrame
	}
	return nil
}

type AuthenticatedFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *AuthenticatedPayload  `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	HmacSha256    []byte                 `protobuf:"bytes,2,opt,name=hmac_sha256,json=hmacSha256,proto3" json:"hmac_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticatedFrame) Reset() {
	*x = AuthenticatedFrame{}
	mi := &file_guest_v2_channel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticatedFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticatedFrame) ProtoMessage() {}

func (x *AuthenticatedFrame) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v2_channel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticatedFrame.ProtoReflect.Descriptor instead.
func (*AuthenticatedFrame) Descriptor() ([]byte, []int) {
	return file_guest_v2_channel_proto_rawDescGZIP(), []int{4}
}

func (x *AuthenticatedFrame) GetPayload() *AuthenticatedPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AuthenticatedFrame) GetHmacSha256() []byte {
	if x != nil {
		return x.HmacSha256
	}
	return nil
}

var File_guest_v2_channel_proto protoreflect.FileDescriptor

const file_guest_v2_channel_proto_rawDesc = "" +
	"\n" +
	"\x16guest/v2/channel.proto\x12\x15grok.desktop.guest.v2\"\x96\x01\n" +
	"\x10ProvisionChannel\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x17\n" +
	"\aboot_id\x18\x02 \x01(\fR\x06bootId\x12\x1f\n" +
	"\vchannel_key\x18\x03 \x01(\fR\n" +
	"channelKey\x12\x1d\n" +
	"\n" +
	"host_nonce\x18\x04 \x01(\fR\thostNonce\"\x9b\x01\n" +
	"\x13ProvisionChannelAck\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x17\n" +
	"\aboot_id\x18\x02 \x01(\fR\x06bootId\x12\x1f\n" +
	"\vguest_nonce\x18\x03 \x01(\fR\n" +
	"guestNonce\x12\x1f\n" +
	"\vhmac_sha256\x18\x04 \x01(\fR\n" +
	"hmacSha256\"\x9b\x01\n" +
	"\x15ProvisionChannelProof\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x17\n" +
	"\aboot_id\x18\x02 \x01(\fR\x06bootId\x12\x1d\n" +
	"\n" +
	"host_nonce\x18\x03 \x01(\fR\thostNonce\x12\x1f\n" +
	"\vguest_nonce\x18\x04 \x01(\fR\n" +
	"guestNonce\"\xab\x02\n" +
	"\x14AuthenticatedPayload\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x17\n" +
	"\aboot_id\x18\x02 \x01(\fR\x06bootId\x12E\n" +
	"\tdirection\x18\x03 \x01(\x0e2'.grok.desktop.guest.v2.ChannelDirectionR\tdirection\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\x12(\n" +
	"\x10deadline_unix_ms\x18\x06 \x01(\x04R\x0edeadlineUnixMs\x12#\n" +
	"\rcontrol_frame\x18\a \x01(\fR\fcontrolFrame\"|\n" +
	"\x12AuthenticatedFrame\x12E\n" +
	"\apayload\x18\x01 \x01(\v2+.grok.desktop.guest.v2.AuthenticatedPayloadR\apayload\x12\x1f\n" +
	"\vhmac_sha256\x18\x02 \x01(\fR\n" +
	"hmacSha256*\x7f\n" +
	"\x10ChannelDirection\x12!\n" +
	"\x1dCHANNEL_DIRECTION_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fCHANNEL_DIRECTION_HOST_TO_GUEST\x10\x01\x12#\n" +
	"\x1fCHANNEL_DIRECTION_GUEST_TO_HOST\x10\x02B_Z]github.com/grok-insider/grok-desktop/native/windows-vm-service/guestchannel/v2;guestchannelv2b\x06proto3"

var (
	file_guest_v2_channel_proto_rawDescOnce sync.Once
	file_guest_v2_channel_proto_rawDescData []byte
)

func file_guest_v2_channel_proto_rawDescGZIP() []byte {
	file_guest_v2_channel_proto_rawDescOnce.Do(func() {
		file_guest_v2_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guest_v2_channel_proto_rawDesc), len(file_guest_v2_channel_proto_rawDesc)))
	})
	return file_guest_v2_channel_proto_rawDescData
}

var file_guest_v2_channel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_guest_v2_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_guest_v2_channel_proto_goTypes = []any{
	(ChannelDirection)(0),         // 0: grok.desktop.guest.v2.ChannelDirection
	(*ProvisionChannel)(nil),      // 1: grok.desktop.guest.v2.ProvisionChannel
	(*ProvisionChannelAck)(nil),   // 2: grok.desktop.guest.v2.ProvisionChannelAck
	(*ProvisionChannelProof)(nil), // 3: grok.desktop.guest.v2.ProvisionChannelProof
	(*AuthenticatedPayload)(nil),  // 4: grok.desktop.guest.v2.AuthenticatedPayload
	(*AuthenticatedFrame)(nil),    // 5: grok.desktop.guest.v2.AuthenticatedFrame
}
var file_guest_v2_channel_proto_depIdxs = []int32{
	0, // 0: grok.desktop.guest.v2.AuthenticatedPayload.direction:type_name -> grok.desktop.guest.v2.ChannelDirection
	4, // 1: grok.desktop.guest.v2.AuthenticatedFrame.payload:type_name -> grok.desktop.guest.v2.AuthenticatedPayload
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_guest_v2_channel_proto_init() }
func file_guest_v2_channel_proto_init() {
	if File_guest_v2_channel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guest_v2_channel_proto_rawDesc), len(file_guest_v2_channel_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_guest_v2_channel_proto_goTypes,
		DependencyIndexes: file_guest_v2_channel_proto_depIdxs,
		EnumInfos:         file_guest_v2_channel_proto_enumTypes,
		MessageInfos:      file_guest_v2_channel_proto_msgTypes,
	}.Build()
	File_guest_v2_channel_proto = out.File
	file_guest_v2_channel_proto_goTypes = nil
	file_guest_v2_channel_proto_depIdxs = nil
}
