import type { DesktopSnapshot } from "./desktopClient";

export const initialSnapshot: DesktopSnapshot = {
  connection: { state: "online", profile: "Interface preview", plan: "No provider execution", interfacePreview: true },
  capabilities: [
    { id: "chat", label: "Grok chat", source: "subscription_acp", available: true },
    { id: "work", label: "Work runtime", source: "desktop", available: true },
    {
      id: "files",
      label: "Local artifact content",
      source: "desktop",
      available: false,
      availability: "unavailable",
      reasonCode: "desktop_preview",
      reason: "File import, opening, and removal require the installed desktop application.",
    },
    { id: "search", label: "Web & X search", source: "subscription_acp", available: true },
    { id: "research", label: "Research", source: "xai_api", available: true },
    { id: "imagine_image", label: "Imagine image", source: "xai_api", available: true },
    { id: "imagine_video", label: "Imagine video", source: "xai_api", available: true },
    { id: "realtime_voice", label: "Realtime voice", source: "xai_api", available: true },
    { id: "browser_automation", label: "Browser automation", source: "managed_addon", available: true },
  ],
  projects: [
    {
      id: "atlas",
      name: "Atlas launch",
      description: "Launch planning, positioning, and customer research.",
      accent: "#4b6b55",
      folders: 3,
      threads: 18,
      updatedAt: "12 min",
      activeRunCount: 1,
      instructions: "Prioritize evidence-backed recommendations and flag assumptions.",
    },
    {
      id: "ops",
      name: "Operations",
      description: "Weekly reporting, vendor analysis, and process documentation.",
      accent: "#50657a",
      folders: 5,
      threads: 31,
      updatedAt: "1 hr",
      activeRunCount: 2,
      instructions: "Keep documents concise and preserve the existing reporting format.",
    },
    {
      id: "personal",
      name: "Personal research",
      description: "Reading notes, travel planning, and long-form research.",
      accent: "#855f48",
      folders: 1,
      threads: 9,
      updatedAt: "Yesterday",
      activeRunCount: 0,
      instructions: "Separate cited facts from suggestions.",
    },
  ],
  runs: [
    {
      id: "run-1",
      title: "Compare launch messaging against competitors",
      projectName: "Atlas launch",
      state: "running",
      progress: 58,
      updatedAt: "Now",
      detail: "Reading 14 source pages and organizing claims",
      steps: [
        { label: "Collect current positioning", state: "done" },
        { label: "Evaluate source claims", state: "active" },
        { label: "Draft comparison matrix", state: "waiting" },
      ],
    },
    {
      id: "run-2",
      title: "Publish the Friday operations brief",
      projectName: "Operations",
      state: "awaiting_approval",
      progress: 76,
      updatedAt: "4 min",
      detail: "Ready to write the reviewed brief to the shared folder",
      steps: [
        { label: "Gather weekly metrics", state: "done" },
        { label: "Prepare brief", state: "done" },
        { label: "Write final document", state: "active" },
      ],
      approval: {
        title: "Write 1 file",
        detail: "Operations/Briefs/2026-07-10.md",
        risk: "low",
      },
    },
    {
      id: "run-3",
      title: "Reconcile vendor invoices",
      projectName: "Operations",
      state: "paused",
      progress: 34,
      updatedAt: "22 min",
      detail: "Paused after detecting two unmatched line items",
      steps: [
        { label: "Import invoices", state: "done" },
        { label: "Match purchase orders", state: "active" },
        { label: "Create exceptions report", state: "waiting" },
      ],
    },
    {
      id: "run-4",
      title: "Summarize customer interviews",
      projectName: "Atlas launch",
      state: "completed",
      progress: 100,
      updatedAt: "Yesterday",
      detail: "Created a themed summary with 12 cited excerpts",
      steps: [
        { label: "Read transcripts", state: "done" },
        { label: "Cluster themes", state: "done" },
        { label: "Write summary", state: "done" },
      ],
    },
  ],
  threads: [
    {
      id: "thread-1",
      title: "Q3 launch narrative",
      projectName: "Atlas launch",
      preview: "I consolidated the strongest proof points and marked the two claims that still need validation.",
      updatedAt: "12 min",
      pinned: true,
      mode: "chat",
    },
    {
      id: "thread-2",
      title: "Competitor landscape",
      projectName: "Atlas launch",
      preview: "The comparison now covers packaging, pricing, and public customer evidence.",
      updatedAt: "46 min",
      mode: "work",
    },
    {
      id: "thread-3",
      title: "Weekly operations brief",
      projectName: "Operations",
      preview: "The final draft is ready for approval before writing to the shared folder.",
      updatedAt: "1 hr",
      mode: "work",
    },
    {
      id: "thread-4",
      title: "Lisbon research notes",
      projectName: "Personal research",
      preview: "I grouped the options by neighborhood and added direct booking sources.",
      updatedAt: "Yesterday",
      mode: "chat",
    },
  ],
  library: [
    { id: "asset-1", name: "Launch narrative.md", type: "document", projectName: "Atlas launch", updatedAt: "12 min", size: "34 KB", contentVersion: 8, metadataRevision: 8 },
    { id: "asset-2", name: "Positioning matrix.csv", type: "data", projectName: "Atlas launch", updatedAt: "34 min", size: "118 KB", contentVersion: 3, metadataRevision: 3 },
    { id: "asset-3", name: "Customer themes.pdf", type: "document", projectName: "Atlas launch", updatedAt: "Yesterday", size: "2.4 MB", contentVersion: 4, metadataRevision: 4 },
    { id: "asset-4", name: "Operations brief.md", type: "document", projectName: "Operations", updatedAt: "1 hr", size: "22 KB", contentVersion: 12, metadataRevision: 12 },
    { id: "asset-5", name: "Quarterly trend.png", type: "image", projectName: "Operations", updatedAt: "2 days", size: "1.8 MB", contentVersion: 2, metadataRevision: 2, palette: "linear-gradient(135deg, #dbe6df, #6f8c78)" },
    { id: "asset-6", name: "Invoice exceptions.xlsx", type: "data", projectName: "Operations", updatedAt: "3 days", size: "724 KB", contentVersion: 6, metadataRevision: 6 },
  ],
  automations: [
    { id: "auto-1", name: "Friday operations brief", projectId: "ops", projectName: "Operations", schedule: "Fri at 4:00 PM", nextRun: "Not scheduled", lastResult: "never", enabled: false, scheduleConfig: { frequency: "weekly", localTime: "16:00", weekday: 5, timeZoneIana: "UTC" }, prompt: "Prepare the reviewed weekly operations brief.", missedRunPolicy: "run_once", overlapPolicy: "queue_one", history: [] },
    { id: "auto-2", name: "Morning competitor scan", projectId: "atlas", projectName: "Atlas launch", schedule: "Weekdays at 8:30 AM", nextRun: "Not scheduled", lastResult: "never", enabled: false, scheduleConfig: { frequency: "weekdays", localTime: "08:30", timeZoneIana: "UTC" }, prompt: "Review official competitor announcements and summarize meaningful changes.", missedRunPolicy: "run_once", overlapPolicy: "skip", history: [] },
    { id: "auto-3", name: "Monthly reading digest", projectId: "personal", projectName: "Personal research", schedule: "1st day at 9:00 AM", nextRun: "Not scheduled", lastResult: "never", enabled: false, scheduleConfig: { frequency: "monthly", localTime: "09:00", dayOfMonth: 1, timeZoneIana: "UTC" }, prompt: "Create a digest from reading notes added this month.", missedRunPolicy: "skip", overlapPolicy: "skip", history: [] },
  ],
  extensions: [
    { id: "browser", name: "Managed browser", description: "A private browser profile for research and web tasks.", kind: "built-in", status: "connected", permissions: ["Selected domains", "Downloads"] },
    { id: "filesystem", name: "Local files", description: "Review and edit files in folders you approve.", kind: "built-in", status: "connected", permissions: ["3 folders"] },
    { id: "wisp", name: "Wisp", description: "Managed desktop and virtual-machine automation backend.", kind: "managed", status: "available", permissions: ["Install required"], recommended: true, version: "0.8.2", updateVersion: "0.9.0" },
    { id: "github", name: "GitHub MCP", description: "Issues, pull requests, repositories, and code search.", kind: "mcp", status: "available", permissions: ["OAuth required"] },
    { id: "linear", name: "Linear MCP", description: "Projects, issues, and team planning context.", kind: "mcp", status: "attention", permissions: ["Reconnect"] },
  ],
};
